/**
 * Catálogo de países con código ISO 3166-1 alpha-2 y código telefónico.
 * Fuente confiable y mantenible: basado en el estándar ISO + ITU-T E.164.
 * No requiere API externa — es autosuficiente y no tiene límite de requests.
 */

export interface Country {
  /** Código ISO 3166-1 alpha-2 (PE, AR, MX, US, ...) */
  code: string
  /** Nombre en español */
  name: string
  /** Prefijo telefónico internacional (+51, +54, +52, ...) */
  callingCode: string
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afganistán', callingCode: '+93' },
  { code: 'AL', name: 'Albania', callingCode: '+355' },
  { code: 'DE', name: 'Alemania', callingCode: '+49' },
  { code: 'AD', name: 'Andorra', callingCode: '+376' },
  { code: 'AO', name: 'Angola', callingCode: '+244' },
  { code: 'AG', name: 'Antigua y Barbuda', callingCode: '+1-268' },
  { code: 'SA', name: 'Arabia Saudita', callingCode: '+966' },
  { code: 'DZ', name: 'Argelia', callingCode: '+213' },
  { code: 'AR', name: 'Argentina', callingCode: '+54' },
  { code: 'AM', name: 'Armenia', callingCode: '+374' },
  { code: 'AU', name: 'Australia', callingCode: '+61' },
  { code: 'AT', name: 'Austria', callingCode: '+43' },
  { code: 'AZ', name: 'Azerbaiyán', callingCode: '+994' },
  { code: 'BS', name: 'Bahamas', callingCode: '+1-242' },
  { code: 'BD', name: 'Bangladés', callingCode: '+880' },
  { code: 'BB', name: 'Barbados', callingCode: '+1-246' },
  { code: 'BH', name: 'Baréin', callingCode: '+973' },
  { code: 'BE', name: 'Bélgica', callingCode: '+32' },
  { code: 'BZ', name: 'Belice', callingCode: '+501' },
  { code: 'BJ', name: 'Benín', callingCode: '+229' },
  { code: 'BY', name: 'Bielorrusia', callingCode: '+375' },
  { code: 'BO', name: 'Bolivia', callingCode: '+591' },
  { code: 'BA', name: 'Bosnia y Herzegovina', callingCode: '+387' },
  { code: 'BW', name: 'Botsuana', callingCode: '+267' },
  { code: 'BR', name: 'Brasil', callingCode: '+55' },
  { code: 'BN', name: 'Brunéi', callingCode: '+673' },
  { code: 'BG', name: 'Bulgaria', callingCode: '+359' },
  { code: 'BF', name: 'Burkina Faso', callingCode: '+226' },
  { code: 'BI', name: 'Burundi', callingCode: '+257' },
  { code: 'BT', name: 'Bután', callingCode: '+975' },
  { code: 'CV', name: 'Cabo Verde', callingCode: '+238' },
  { code: 'KH', name: 'Camboya', callingCode: '+855' },
  { code: 'CM', name: 'Camerún', callingCode: '+237' },
  { code: 'CA', name: 'Canadá', callingCode: '+1' },
  { code: 'QA', name: 'Catar', callingCode: '+974' },
  { code: 'TD', name: 'Chad', callingCode: '+235' },
  { code: 'CL', name: 'Chile', callingCode: '+56' },
  { code: 'CN', name: 'China', callingCode: '+86' },
  { code: 'CY', name: 'Chipre', callingCode: '+357' },
  { code: 'CO', name: 'Colombia', callingCode: '+57' },
  { code: 'KM', name: 'Comoras', callingCode: '+269' },
  { code: 'CG', name: 'Congo', callingCode: '+242' },
  { code: 'CD', name: 'Congo (RDC)', callingCode: '+243' },
  { code: 'KR', name: 'Corea del Sur', callingCode: '+82' },
  { code: 'KP', name: 'Corea del Norte', callingCode: '+850' },
  { code: 'CI', name: 'Costa de Marfil', callingCode: '+225' },
  { code: 'CR', name: 'Costa Rica', callingCode: '+506' },
  { code: 'HR', name: 'Croacia', callingCode: '+385' },
  { code: 'CU', name: 'Cuba', callingCode: '+53' },
  { code: 'DK', name: 'Dinamarca', callingCode: '+45' },
  { code: 'DM', name: 'Dominica', callingCode: '+1-767' },
  { code: 'EC', name: 'Ecuador', callingCode: '+593' },
  { code: 'EG', name: 'Egipto', callingCode: '+20' },
  { code: 'SV', name: 'El Salvador', callingCode: '+503' },
  { code: 'AE', name: 'Emiratos Árabes', callingCode: '+971' },
  { code: 'ER', name: 'Eritrea', callingCode: '+291' },
  { code: 'SK', name: 'Eslovaquia', callingCode: '+421' },
  { code: 'SI', name: 'Eslovenia', callingCode: '+386' },
  { code: 'ES', name: 'España', callingCode: '+34' },
  { code: 'US', name: 'Estados Unidos', callingCode: '+1' },
  { code: 'EE', name: 'Estonia', callingCode: '+372' },
  { code: 'ET', name: 'Etiopía', callingCode: '+251' },
  { code: 'PH', name: 'Filipinas', callingCode: '+63' },
  { code: 'FI', name: 'Finlandia', callingCode: '+358' },
  { code: 'FJ', name: 'Fiyi', callingCode: '+679' },
  { code: 'FR', name: 'Francia', callingCode: '+33' },
  { code: 'GA', name: 'Gabón', callingCode: '+241' },
  { code: 'GM', name: 'Gambia', callingCode: '+220' },
  { code: 'GE', name: 'Georgia', callingCode: '+995' },
  { code: 'GH', name: 'Ghana', callingCode: '+233' },
  { code: 'GD', name: 'Granada', callingCode: '+1-473' },
  { code: 'GR', name: 'Grecia', callingCode: '+30' },
  { code: 'GT', name: 'Guatemala', callingCode: '+502' },
  { code: 'GN', name: 'Guinea', callingCode: '+224' },
  { code: 'GQ', name: 'Guinea Ecuatorial', callingCode: '+240' },
  { code: 'GW', name: 'Guinea-Bisáu', callingCode: '+245' },
  { code: 'GY', name: 'Guyana', callingCode: '+592' },
  { code: 'HT', name: 'Haití', callingCode: '+509' },
  { code: 'HN', name: 'Honduras', callingCode: '+504' },
  { code: 'HU', name: 'Hungría', callingCode: '+36' },
  { code: 'IN', name: 'India', callingCode: '+91' },
  { code: 'ID', name: 'Indonesia', callingCode: '+62' },
  { code: 'IQ', name: 'Irak', callingCode: '+964' },
  { code: 'IR', name: 'Irán', callingCode: '+98' },
  { code: 'IE', name: 'Irlanda', callingCode: '+353' },
  { code: 'IS', name: 'Islandia', callingCode: '+354' },
  { code: 'MH', name: 'Islas Marshall', callingCode: '+692' },
  { code: 'SB', name: 'Islas Salomón', callingCode: '+677' },
  { code: 'IL', name: 'Israel', callingCode: '+972' },
  { code: 'IT', name: 'Italia', callingCode: '+39' },
  { code: 'JM', name: 'Jamaica', callingCode: '+1-876' },
  { code: 'JP', name: 'Japón', callingCode: '+81' },
  { code: 'JO', name: 'Jordania', callingCode: '+962' },
  { code: 'KZ', name: 'Kazajistán', callingCode: '+7' },
  { code: 'KE', name: 'Kenia', callingCode: '+254' },
  { code: 'KG', name: 'Kirguistán', callingCode: '+996' },
  { code: 'KI', name: 'Kiribati', callingCode: '+686' },
  { code: 'KW', name: 'Kuwait', callingCode: '+965' },
  { code: 'LA', name: 'Laos', callingCode: '+856' },
  { code: 'LS', name: 'Lesoto', callingCode: '+266' },
  { code: 'LV', name: 'Letonia', callingCode: '+371' },
  { code: 'LB', name: 'Líbano', callingCode: '+961' },
  { code: 'LR', name: 'Liberia', callingCode: '+231' },
  { code: 'LY', name: 'Libia', callingCode: '+218' },
  { code: 'LI', name: 'Liechtenstein', callingCode: '+423' },
  { code: 'LT', name: 'Lituania', callingCode: '+370' },
  { code: 'LU', name: 'Luxemburgo', callingCode: '+352' },
  { code: 'MG', name: 'Madagascar', callingCode: '+261' },
  { code: 'MY', name: 'Malasia', callingCode: '+60' },
  { code: 'MW', name: 'Malaui', callingCode: '+265' },
  { code: 'MV', name: 'Maldivas', callingCode: '+960' },
  { code: 'ML', name: 'Malí', callingCode: '+223' },
  { code: 'MT', name: 'Malta', callingCode: '+356' },
  { code: 'MA', name: 'Marruecos', callingCode: '+212' },
  { code: 'MU', name: 'Mauricio', callingCode: '+230' },
  { code: 'MR', name: 'Mauritania', callingCode: '+222' },
  { code: 'MX', name: 'México', callingCode: '+52' },
  { code: 'FM', name: 'Micronesia', callingCode: '+691' },
  { code: 'MD', name: 'Moldavia', callingCode: '+373' },
  { code: 'MC', name: 'Mónaco', callingCode: '+377' },
  { code: 'MN', name: 'Mongolia', callingCode: '+976' },
  { code: 'ME', name: 'Montenegro', callingCode: '+382' },
  { code: 'MZ', name: 'Mozambique', callingCode: '+258' },
  { code: 'MM', name: 'Myanmar', callingCode: '+95' },
  { code: 'NA', name: 'Namibia', callingCode: '+264' },
  { code: 'NR', name: 'Nauru', callingCode: '+674' },
  { code: 'NP', name: 'Nepal', callingCode: '+977' },
  { code: 'NI', name: 'Nicaragua', callingCode: '+505' },
  { code: 'NE', name: 'Níger', callingCode: '+227' },
  { code: 'NG', name: 'Nigeria', callingCode: '+234' },
  { code: 'NO', name: 'Noruega', callingCode: '+47' },
  { code: 'NZ', name: 'Nueva Zelanda', callingCode: '+64' },
  { code: 'OM', name: 'Omán', callingCode: '+968' },
  { code: 'NL', name: 'Países Bajos', callingCode: '+31' },
  { code: 'PK', name: 'Pakistán', callingCode: '+92' },
  { code: 'PW', name: 'Palaos', callingCode: '+680' },
  { code: 'PA', name: 'Panamá', callingCode: '+507' },
  { code: 'PG', name: 'Papúa Nueva Guinea', callingCode: '+675' },
  { code: 'PY', name: 'Paraguay', callingCode: '+595' },
  { code: 'PE', name: 'Perú', callingCode: '+51' },
  { code: 'PL', name: 'Polonia', callingCode: '+48' },
  { code: 'PT', name: 'Portugal', callingCode: '+351' },
  { code: 'GB', name: 'Reino Unido', callingCode: '+44' },
  { code: 'CF', name: 'Rep. Centroafricana', callingCode: '+236' },
  { code: 'CZ', name: 'Rep. Checa', callingCode: '+420' },
  { code: 'DO', name: 'Rep. Dominicana', callingCode: '+1-809' },
  { code: 'RO', name: 'Rumanía', callingCode: '+40' },
  { code: 'RU', name: 'Rusia', callingCode: '+7' },
  { code: 'RW', name: 'Ruanda', callingCode: '+250' },
  { code: 'KN', name: 'San Cristóbal y Nieves', callingCode: '+1-869' },
  { code: 'SM', name: 'San Marino', callingCode: '+378' },
  { code: 'VC', name: 'San Vicente y las Granadinas', callingCode: '+1-784' },
  { code: 'LC', name: 'Santa Lucía', callingCode: '+1-758' },
  { code: 'ST', name: 'Santo Tomé y Príncipe', callingCode: '+239' },
  { code: 'SN', name: 'Senegal', callingCode: '+221' },
  { code: 'RS', name: 'Serbia', callingCode: '+381' },
  { code: 'SC', name: 'Seychelles', callingCode: '+248' },
  { code: 'SL', name: 'Sierra Leona', callingCode: '+232' },
  { code: 'SG', name: 'Singapur', callingCode: '+65' },
  { code: 'SY', name: 'Siria', callingCode: '+963' },
  { code: 'SO', name: 'Somalia', callingCode: '+252' },
  { code: 'LK', name: 'Sri Lanka', callingCode: '+94' },
  { code: 'ZA', name: 'Sudáfrica', callingCode: '+27' },
  { code: 'SD', name: 'Sudán', callingCode: '+249' },
  { code: 'SS', name: 'Sudán del Sur', callingCode: '+211' },
  { code: 'SE', name: 'Suecia', callingCode: '+46' },
  { code: 'CH', name: 'Suiza', callingCode: '+41' },
  { code: 'SR', name: 'Surinam', callingCode: '+597' },
  { code: 'TH', name: 'Tailandia', callingCode: '+66' },
  { code: 'TZ', name: 'Tanzania', callingCode: '+255' },
  { code: 'TJ', name: 'Tayikistán', callingCode: '+992' },
  { code: 'TL', name: 'Timor Oriental', callingCode: '+670' },
  { code: 'TG', name: 'Togo', callingCode: '+228' },
  { code: 'TO', name: 'Tonga', callingCode: '+676' },
  { code: 'TT', name: 'Trinidad y Tobago', callingCode: '+1-868' },
  { code: 'TN', name: 'Túnez', callingCode: '+216' },
  { code: 'TM', name: 'Turkmenistán', callingCode: '+993' },
  { code: 'TR', name: 'Turquía', callingCode: '+90' },
  { code: 'TV', name: 'Tuvalu', callingCode: '+688' },
  { code: 'UA', name: 'Ucrania', callingCode: '+380' },
  { code: 'UG', name: 'Uganda', callingCode: '+256' },
  { code: 'UY', name: 'Uruguay', callingCode: '+598' },
  { code: 'UZ', name: 'Uzbekistán', callingCode: '+998' },
  { code: 'VU', name: 'Vanuatu', callingCode: '+678' },
  { code: 'VA', name: 'Vaticano', callingCode: '+379' },
  { code: 'VE', name: 'Venezuela', callingCode: '+58' },
  { code: 'VN', name: 'Vietnam', callingCode: '+84' },
  { code: 'YE', name: 'Yemen', callingCode: '+967' },
  { code: 'DJ', name: 'Yibuti', callingCode: '+253' },
  { code: 'ZM', name: 'Zambia', callingCode: '+260' },
  { code: 'ZW', name: 'Zimbabue', callingCode: '+263' },
]

export const DEFAULT_COUNTRY: Country = COUNTRIES.find(c => c.code === 'PE') ?? COUNTRIES[0]

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code)
}

export function getCountryCallingCode(code: string): string {
  return getCountryByCode(code)?.callingCode ?? ''
}
